name: coin-data-source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: coin-data
    required: false
  - name: API_KEY
    inputType: Secret
    defaultValue: API_KEY-key
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
