name: coin-data-frontend
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: ''
    defaultValue: coin-data-updated
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: streamlit_file.py
