name: coin-data-frontend
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: updated-coin-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: streamlit_file.py
