name: coin-price-transformation
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: coin-data-gbp
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: coin-data-updated
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
