name: usd-to-gbp-transformation
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: coin-data
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: coin-data-gbp
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
